[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
monitor_echo = yes
monitor_eol = LF
board_build.filesystem = littlefs
lib_deps =
	bblanchon/ArduinoJson@^7.1.0
	esphome/AsyncTCP-esphome@^2.0.0
	esphome/ESPAsyncWebServer-esphome@^3.1.0